<a href="https://colab.research.google.com/github/GYARASIDDHARTHA/PROJECT.0/blob/main/MINOR_PROJECT%3D_image_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install ipython_autotime
%load_ext autotime

time: 1.88 ms (started: 2021-06-25 04:08:16 +00:00)


In [2]:
!pip install bing_image_downloader

time: 3.35 s (started: 2021-06-25 04:08:27 +00:00)


In [3]:
!mkdir images

time: 120 ms (started: 2021-06-25 04:08:43 +00:00)


In [4]:
from bing_image_downloader import downloader
downloader.download("car",limit=30,output_dir='images',adult_filter_off=True)

[%] Downloading Images to /content/images/car


[!!]Indexing page: 1

[%] Indexed 30 Images on Page 1.


[%] Downloading Image #1 from http://www.carbodydesign.com/archive/2009/08/05-sv-9-competizione-images/SV-9-Competizione-4-lg.jpg
[%] File Downloaded !

[%] Downloading Image #2 from https://static.carthrottle.com/workspace/uploads/posts/2017/12/0fcad9c9368abebdbfb8aaf0211bf96b.jpg
[%] File Downloaded !

[%] Downloading Image #3 from http://jaikrishnaamaruti.com/uploads/truevalue_cars/0_27-01-2018_16-03-53.jpg
[%] File Downloaded !

[%] Downloading Image #4 from https://icdn-4.motor1.com/images/mgl/8gJ93/s1/amc-amx-the-first-true-sports-car-of-the-1960s.jpg
[%] File Downloaded !

[%] Downloading Image #5 from http://farm9.staticflickr.com/8012/7170866083_8504026441_o.jpg
[%] File Downloaded !

[%] Downloading Image #6 from http://dmi3w0goirzgw.cloudfront.net/gallery-images/1600/406000/600/406638.jpg
[%] File Downloaded !

[%] Downloading Image #7 from http://smclassiccars.com/upload

In [5]:
from bing_image_downloader import downloader
downloader.download("ice cream cone",limit=30,output_dir='images',adult_filter_off=True)

[%] Downloading Images to /content/images/ice cream cone


[!!]Indexing page: 1

[%] Indexed 30 Images on Page 1.


[%] Downloading Image #1 from http://graphics8.nytimes.com/images/2013/06/02/magazine/02wmt/02wmt-superJumbo-v3.jpg
[%] File Downloaded !

[%] Downloading Image #2 from https://americacomesalive.com/i/ice-cream-cone.jpg
[%] File Downloaded !

[%] Downloading Image #3 from https://www.thespruceeats.com/thmb/3zSpyarxfOBVAZS3CNJYOBGk26s=/3000x1687/smart/filters:no_upscale()/IceCreamConeCupcakesHERO-ef1da5f5b4be42129e420ad1b8088b9b.jpg
[%] File Downloaded !

[%] Downloading Image #4 from https://img1.southernliving.timeinc.net/sites/default/files/styles/4_3_horizontal_-_1200x900/public/image/2017/07/main/ice-cream-cones.jpg?itok=9I9Q7gKA
[%] File Downloaded !

[%] Downloading Image #5 from http://www.koshericecream.com/wp-content/uploads/magictoolbox_cache/640ca855e591fa5c6759d336b1ca786b/original/2118662499/41404-24-Pk-Nutty-Cone-D-UPC-0-91404-21150-5.jpg
[%] File Downloaded

In [6]:
from bing_image_downloader import downloader
downloader.download("man face",limit=30,output_dir='images',adult_filter_off=True)

[%] Downloading Images to /content/images/man face


[!!]Indexing page: 1

[%] Indexed 31 Images on Page 1.


[%] Downloading Image #1 from https://i.pinimg.com/originals/28/7f/46/287f4625ef9a3d7c73fc120cce3b3b10.jpg
[%] File Downloaded !

[%] Downloading Image #2 from https://i.pinimg.com/originals/71/dd/c6/71ddc6fe21d7574076722c3b847d423a.jpg
[%] File Downloaded !

[%] Downloading Image #3 from https://i.pinimg.com/736x/30/20/41/30204184ec63cf3bcdedfa1e5b4456fe--property-brothers-the-property.jpg
[%] File Downloaded !

[%] Downloading Image #4 from https://i.pinimg.com/originals/64/1a/7d/641a7d2cd8832fbd98467f1529f89160.jpg
[%] File Downloaded !

[%] Downloading Image #5 from https://i.pinimg.com/474x/96/da/b2/96dab2ec9e198f1a05b5f85675983f06.jpg
[%] File Downloaded !

[%] Downloading Image #6 from https://i.pinimg.com/originals/5a/99/ab/5a99abe5510bc866cdcaa0acad9cb4b2.jpg
[%] File Downloaded !

[%] Downloading Image #7 from https://i.pinimg.com/originals/eb/8f/a2/eb8fa2eb1bd69b3d56

In [7]:
import numpy as np

a = np.array([[1,2,3,4,5],
              [4,5,6,7,8]])
a.ndim

2

time: 11.9 ms (started: 2021-06-25 04:17:58 +00:00)


In [8]:
a.flatten()

array([1, 2, 3, 4, 5, 4, 5, 6, 7, 8])

time: 13.9 ms (started: 2021-06-25 04:18:13 +00:00)


In [9]:
#preprocessing

import os
import matplotlib.pyplot as plt
import numpy as np
from skimage.io import imread
from skimage.transform import resize

target = []
images = []
flat_data = []

DATADIR ="/content/images"
CATEGORIES = ['car','ice cream cone','man face']

for category in CATEGORIES:
  class_num = CATEGORIES.index(category)
  path = os.path.join(DATADIR,category)
  for img in os.listdir(path):
    img_array = imread(os.path.join(path,img))
    #print(img_array.shape)
    #plt.imshow(img_array)
    img_resized = resize(img_array,(150,150,3))
    flat_data.append(img_resized.flatten())
    images.append(img_resized)
    target.append(class_num)


flat_data =  np.array(flat_data)
target = np.array(target)
images = np.array(images)

time: 1min 4s (started: 2021-06-25 04:20:54 +00:00)


In [10]:
len(flat_data[0])

67500

time: 10 ms (started: 2021-06-25 04:39:20 +00:00)


In [11]:
150*150*3

67500

time: 5.67 ms (started: 2021-06-25 04:39:43 +00:00)


In [12]:
target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

time: 9.81 ms (started: 2021-06-25 04:43:32 +00:00)


In [13]:
unique,count = np.unique(target,return_counts=True)
plt.bar(CATEGORIES,count)

<BarContainer object of 3 artists>

time: 199 ms (started: 2021-06-25 04:44:26 +00:00)


In [14]:
# split data into Traning and testing
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(flat_data,target,
                                  test_size=0.3,random_state=109)

time: 322 ms (started: 2021-06-25 04:44:50 +00:00)


In [15]:
from sklearn.model_selection import GridSearchCV
from sklearn import svm
param_grid = [
              {'C':[1,10,100,1000],'kernel':['linear']},
              {'C':[1,10,100,1000],'gamma':[0.001,0.0001],'kernel':['rbf']},
]

svc = svm.SVC(probability=True)
clf = GridSearchCV(svc,param_grid)
clf.fit(x_train,y_train)

GridSearchCV(cv=None, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=True, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid=[{'C': [1, 10, 100, 1000], 'kernel': ['linear']},
                         {'C': [1, 10, 100, 1000], 'gamma': [0.001, 0.0001],
                          'kernel': ['rbf']}],
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

time: 1min 28s (started: 2021-06-25 04:45:21 +00:00)


In [16]:
y_pred = clf.predict(x_test)
y_pred

array([1, 2, 1, 1, 2, 1, 0, 0, 2, 2, 2, 0, 1, 1, 2, 2, 2, 1, 2, 2, 2, 2,
       2, 2, 2, 0, 1])

time: 149 ms (started: 2021-06-25 04:47:08 +00:00)


In [17]:
y_test

array([1, 0, 1, 2, 2, 1, 0, 1, 1, 0, 1, 0, 1, 2, 2, 1, 2, 1, 0, 1, 2, 2,
       2, 0, 0, 0, 1])

time: 4.34 ms (started: 2021-06-25 04:47:27 +00:00)


In [18]:
from sklearn.metrics import accuracy_score,confusion_matrix

time: 869 µs (started: 2021-06-25 04:47:43 +00:00)


In [19]:
accuracy_score(y_pred,y_test)

0.5555555555555556

time: 8.12 ms (started: 2021-06-25 04:48:11 +00:00)


In [20]:
confusion_matrix(y_pred,y_test)

array([[3, 1, 0],
       [0, 6, 2],
       [5, 4, 6]])

time: 8.62 ms (started: 2021-06-25 04:48:31 +00:00)


In [21]:
# save the model using pickle library
import pickle
pickle.dump(clf,open('img_model.p','wb'))

time: 47.1 ms (started: 2021-06-25 04:49:28 +00:00)


In [22]:
 model = pickle.load(open('img_model.p','rb'))

time: 25.8 ms (started: 2021-06-25 04:50:06 +00:00)


In [30]:
#Testing a brand new Image
flat_data = []
url = input('Enter your URL')
img = imread(url)
img_resized = resize(img,(150,150,3))
flat_data.append(img_resized.flatten())
flat_data = np.array(flat_data)
print(img.shape)
plt.imshow(img_resized)
y_out = model.predict(flat_data)
y_out = CATEGORIES[y_out[0]]
print(f' PREDICTED OUTPUT: {y_out}')

Enter your URLhttps://th.bing.com/th/id/OIP.DUvoVlm7jwmhuRxcZzEoCgHaEo?pid=ImgDet&rs=1
(296, 474, 3)
 PREDICTED OUTPUT: car


time: 1min 12s (started: 2021-06-25 05:05:23 +00:00)
